//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperz.SharpLeech.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperz.SharpLeech.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!-- AUTO GENERATED ERROR LOG --&gt;
        ///
        ///&lt;Errors&gt;&lt;/Errors&gt;.
        /// </summary>
        public static string ErrorLogTemplate {
            get {
                return ResourceManager.GetString("ErrorLogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        public static string FormContentType {
            get {
                return ResourceManager.GetString("FormContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------26919256316738
        ///Content-Disposition: form-data; name=&quot;st&quot;
        ///
        ///0
        ///-----------------------------26919256316738
        ///Content-Disposition: form-data; name=&quot;act&quot;
        ///
        ///Post
        ///-----------------------------26919256316738
        ///Content-Disposition: form-data; name=&quot;s&quot;
        ///
        ///
        ///-----------------------------26919256316738
        ///Content-Disposition: form-data; name=&quot;f&quot;
        ///
        ///{2}
        ///-----------------------------26919256316738
        ///Content-Disposition: form-data; name=&quot;auth_key&quot;
        ///
        ///[auth_key]
        ///----------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IPBoard_200_ContentTemplate {
            get {
                return ResourceManager.GetString("IPBoard_200_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipart/form-data; boundary=---------------------------26919256316738.
        /// </summary>
        public static string IPBoard_200_ContentType {
            get {
                return ResourceManager.GetString("IPBoard_200_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CookieDate=1&amp;UserName={0}&amp;PassWord={1}.
        /// </summary>
        public static string IPBoard_200_Login {
            get {
                return ResourceManager.GetString("IPBoard_200_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------269432483414243
        ///Content-Disposition: form-data; name=&quot;TopicTitle&quot;
        ///
        ///{0}
        ///-----------------------------269432483414243
        ///Content-Disposition: form-data; name=&quot;TopicDesc&quot;
        ///
        ///
        ///-----------------------------269432483414243
        ///Content-Disposition: form-data; name=&quot;poll_question&quot;
        ///
        ///
        ///-----------------------------269432483414243
        ///Content-Disposition: form-data; name=&quot;ed-0_wysiwyg_used&quot;
        ///
        ///0
        ///-----------------------------269432483414243
        ///Content-Disposition: form-data; name=&quot;editor_ids[ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IPBoard_300_ContentTemplate {
            get {
                return ResourceManager.GetString("IPBoard_300_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipart/form-data; boundary=---------------------------269432483414243.
        /// </summary>
        public static string IPBoard_300_ContentType {
            get {
                return ResourceManager.GetString("IPBoard_300_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username={0}&amp;password={1}&amp;rememberMe=1.
        /// </summary>
        public static string IPBoard_300_Login {
            get {
                return ResourceManager.GetString("IPBoard_300_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth_key={2}&amp;referer={3}&amp;username={0}&amp;password={1}&amp;rememberMe=1.
        /// </summary>
        public static string IPBoard_314_Login {
            get {
                return ResourceManager.GetString("IPBoard_314_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject={0}&amp;description=&amp;tag_select=&amp;captcha_code=null&amp;addbbcode18=%23&amp;addbbcode20=12&amp;helpbox=null&amp;message={1}&amp;via=[via]&amp;poll_title=&amp;add_poll_option_text=&amp;poll_length=&amp;captcha_id=null&amp;mode=newtopic&amp;sid=[sid]&amp;f={2}&amp;post_icon={3}&amp;post=Submit.
        /// </summary>
        public static string phpBB_200_ContentTemplate {
            get {
                return ResourceManager.GetString("phpBB_200_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        public static string phpBB_200_ContentType {
            get {
                return ResourceManager.GetString("phpBB_200_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username={0}&amp;password={1}&amp;autologin=on&amp;redirect=&amp;login=Log+in.
        /// </summary>
        public static string phpBB_200_Login {
            get {
                return ResourceManager.GetString("phpBB_200_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------52261646328134
        ///Content-Disposition: form-data; name=&quot;icon&quot;
        ///
        ///{3}
        ///-----------------------------52261646328134
        ///Content-Disposition: form-data; name=&quot;subject&quot;
        ///
        ///{0}
        ///-----------------------------52261646328134
        ///Content-Disposition: form-data; name=&quot;addbbcode20&quot;
        ///
        ///100
        ///-----------------------------52261646328134
        ///Content-Disposition: form-data; name=&quot;message&quot;
        ///
        ///{1}
        ///-----------------------------52261646328134
        ///Content-Disposition: form-data; name=&quot;lastclick&quot;
        ///
        ///[creation_time [rest of string was truncated]&quot;;.
        /// </summary>
        public static string phpBB_300_ContentTemplate {
            get {
                return ResourceManager.GetString("phpBB_300_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipart/form-data; boundary=---------------------------52261646328134.
        /// </summary>
        public static string phpBB_300_ContentType {
            get {
                return ResourceManager.GetString("phpBB_300_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username={0}&amp;password={1}&amp;autologin=on&amp;redirect=index.php&amp;login=Login&amp;redirect=.%2Fucp.php%3Fmode%3Dlogin.
        /// </summary>
        public static string phpBB_300_Login {
            get {
                return ResourceManager.GetString("phpBB_300_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string SiteReaderExt {
            get {
                return ResourceManager.GetString("SiteReaderExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Hyperz.SharpLeech.SiteReaders
        ///{
        ///	public class [__CLASS__] : SiteReader
        ///	{
        ///		public [__CLASS__](string siteName,
        ///						   string baseUrl,
        ///						   string siteTypeName,
        ///						   int topicsPerPage,
        ///						   Dictionary&lt;string, int&gt; sections,
        ///						   string defaultEncoding = &quot;&quot;,
        ///						   bool allowRedirects = false,
        ///						   bool useFriendlyLinks = false)
        ///			: base(siteName, baseUrl, siteTypeName, topicsPerPage, sections,
        ///				   defaultEncoding, allowRedirects, useFriendlyLinks)
        ///		{ }
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SiteReaderTemplate {
            get {
                return ResourceManager.GetString("SiteReaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Xml;
        ///using System.Xml.Linq;
        ///using Hyperz.SharpLeech.Engine;
        ///using Hyperz.SharpLeech.Engine.Html;
        ///using Hyperz.SharpLeech.Engine.Net;
        ///
        ///using Res = Hyperz.SharpLeech.Engine.Properties.Resources;
        ///
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SiteReaderTemplateHeader {
            get {
                return ResourceManager.GetString("SiteReaderTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows; N; {0}; 64Bit:{1}; .NET CLR {2}) SLEngine/{3} SharpLeech/2.x.x.
        /// </summary>
        public static string UserAgentFormat {
            get {
                return ResourceManager.GetString("UserAgentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject={0}&amp;message={1}&amp;wysiwyg=0&amp;taglist=&amp;iconid={3}&amp;s=&amp;securitytoken=[securitytoken]&amp;f={2}&amp;do=postthread&amp;posthash=&amp;poststarttime=&amp;loggedinuser=[loggedinuser]&amp;sbutton=Submit+New+Thread&amp;parseurl=1&amp;parseame=1&amp;parseame_check=1&amp;emailupdate=9999&amp;polloptions=2.
        /// </summary>
        public static string vBulletin_300_ContentTemplate {
            get {
                return ResourceManager.GetString("vBulletin_300_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        public static string vBulletin_300_ContentType {
            get {
                return ResourceManager.GetString("vBulletin_300_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cookieuser=1&amp;do=login&amp;vb_login_username={0}&amp;vb_login_password={1}.
        /// </summary>
        public static string vBulletin_300_Login {
            get {
                return ResourceManager.GetString("vBulletin_300_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject={0}&amp;message={1}&amp;wysiwyg=0&amp;taglist=&amp;iconid={3}&amp;s=&amp;securitytoken=[securitytoken]&amp;f={2}&amp;do=postthread&amp;posthash=&amp;poststarttime=&amp;loggedinuser=[loggedinuser]&amp;sbutton=Submit+New+Thread&amp;parseurl=1&amp;parseame=1&amp;parseame_check=1&amp;emailupdate=9999&amp;polloptions=2.
        /// </summary>
        public static string vBulletin_400_ContentTemplate {
            get {
                return ResourceManager.GetString("vBulletin_400_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        public static string vBulletin_400_ContentType {
            get {
                return ResourceManager.GetString("vBulletin_400_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb_login_username={0}&amp;vb_login_password={1}&amp;cookieuser=1&amp;s=&amp;securitytoken=guest&amp;do=login&amp;vb_login_md5password={2}&amp;vb_login_md5password_utf={3}.
        /// </summary>
        public static string vBulletin_400_Login {
            get {
                return ResourceManager.GetString("vBulletin_400_Login", resourceCulture);
            }
        }
    }
}
