//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperz.SharpLeech.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperz.SharpLeech.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} :: {1}.
        /// </summary>
        internal static string ChatTitleFormat {
            get {
                return ResourceManager.GetString("ChatTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioStations.txt.
        /// </summary>
        internal static string FileRadioStations {
            get {
                return ResourceManager.GetString("FileRadioStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0} {1} *.
        /// </summary>
        internal static string IrcActionMessageFormat {
            get {
                return ResourceManager.GetString("IrcActionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Leech.
        /// </summary>
        internal static string IrcChannel {
            get {
                return ResourceManager.GetString("IrcChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}: {2}.
        /// </summary>
        internal static string IrcMessageFormat {
            get {
                return ResourceManager.GetString("IrcMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.
        /// </summary>
        internal static string IrcNickNameFormat {
            get {
                return ResourceManager.GetString("IrcNickNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6667.
        /// </summary>
        internal static string IrcPort {
            get {
                return ResourceManager.GetString("IrcPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing SharpLeech.
        /// </summary>
        internal static string IrcQuitMessage {
            get {
                return ResourceManager.GetString("IrcQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLClient {0:x}.
        /// </summary>
        internal static string IrcRealNameFormat {
            get {
                return ResourceManager.GetString("IrcRealNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to irc.dal.net.
        /// </summary>
        internal static string IrcServer {
            get {
                return ResourceManager.GetString("IrcServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #  ___  _                   _                   _   
        ///# / __&gt;| |_  ___  _ _  ___ | |   ___  ___  ___ | |_ 
        ///# \__ \| . |&lt;_&gt; || &apos;_&gt;| . \| |_ / ._&gt;/ ._&gt;/ | &apos;| . |
        ///# &lt;___/|_|_|&lt;___||_|  |  _/|___|\___.\___.\_|_.|_|_|
        ///#                     |_|                           
        ///# 
        ///# ==================================================
        ///#
        ///# Commands:
        ///#   /SAY [message]       : sends a message
        ///#   /ME [action_message] : sends an action message
        ///#   /CLEAR, /CLR         : clears the chat screen
        ///# 
        ///# =============== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IrcWelcomeMessage {
            get {
                return ResourceManager.GetString("IrcWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings seem to have invalid values.
        ///Aborting....
        /// </summary>
        internal static string MsgInvalidValues {
            get {
                return ResourceManager.GetString("MsgInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We seem to have a problem logging you in. Make sure your login details are correct and that the target site is online. As an alternative you can try to login via a web browser. However, this is NOT RECOMMENDED!
        ///
        ///Would you like to use a web browser to login?.
        /// </summary>
        internal static string MsgLoginFailed {
            get {
                return ResourceManager.GetString("MsgLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset _all_ settings?.
        /// </summary>
        internal static string MsgResetSettings {
            get {
                return ResourceManager.GetString("MsgResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the settings you changed will only take affect the next time you start SharpLeech..
        /// </summary>
        internal static string MsgRestartRequired {
            get {
                return ResourceManager.GetString("MsgRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Now Bumpin&apos; {1}.
        /// </summary>
        internal static string RadioTitleFormat {
            get {
                return ResourceManager.GetString("RadioTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpLeech {0}.
        /// </summary>
        internal static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
    }
}
